BEGIN;
CREATE TABLE IF NOT EXISTS public.document_chunks (
    chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES public.documents(document_id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    char_start INTEGER NOT NULL,
    char_end INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_document_chunks_document_index UNIQUE (document_id, chunk_index),
    CONSTRAINT ck_document_chunks_range CHECK (char_start >= 0 AND char_end > char_start),
    CONSTRAINT ck_document_chunks_index CHECK (chunk_index >= 0),
    CONSTRAINT ck_document_chunks_content CHECK (length(btrim(content)) > 0)
);
COMMIT;
